application: five-votes
version: 1
#runtime: python
api_version: 1

runtime: python27
threadsafe: true

libraries:
- name: django                                                                  
  version: latest                                                               
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest 


handlers:
- url: /css
  static_dir: css

- url: /fancybox
  static_dir: fancybox

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /img
  static_dir: img

- url: /channel.html
  static_files: channel.html
  upload: channel.html
  expiration: "400d"

- url: /test_fb.html
  static_files: test_fb.html
  upload: test_fb.html

- url: /test_fancybox.html
  static_files: test_fancybox.html
  upload: test_fancybox.html

#- url: /.*
#  script: canvas4.py

#- url: /.*
#  script: example.py

#- url: /.*
#  script: test_app.app

- url: /.*
  script: canvas4.app

#- url: /.*
#  script: example.app




