<div id="contentwrapper">
<div id="contentcolumn">
  <div id="super_top_container" class="innertube">
      <div id="main_container" style="margin-top:20px;margin-bottom:20px;">
      </div> <!-- main container -->
      <div id="prev_questions">
      </div> <!-- prev_questions -->
  </div> <!-- super_top_container -->
</div>
</div> <!-- contentwrapper -->


<div id="rightcolumn">
  <div id="right_col">
     <div class="mytube">
         <div style="text-align:left;" id="faces_div"></div>
         <p class="tiny">{% trans %}Questions about this app? Leave them here:{% endtrans %}</p>
         <div class="fb-comments" data-href="http://five-votes.appspot.com" data-num-posts="4" data-width="305"></div>
     </div>
  </div>
</div>

