<div id="main_container">
</div> <!-- main container -->

<br />

<div class="vote_link add_ans_class add_ans_link">
      <div class="mytube">
        <a href="#" onclick="add_ans_link_func();return false;">{% trans %}comment{% endtrans %}</a>
      </div>
</div>

<br />

<div class="vote_link add_ans_class add_ans_link" style="margin-bottom:20px;">
    <div class="mytube">
       <a href="{{BASE_URL}}/add" target="_top">{% trans %}Create your own questions!{% endtrans %}</a>
    </div>
</div>
