<div id="main_container">
</div> <!-- main container -->

<div class="comments_box">
          <div style="float:left;padding-top:20px;"><div class="fb-comments" data-href="{{BASE_URL}}/q{{question_key_name}}" data-num-posts="4" data-width="450"></div></div>

<!-- <div style="clear:both;float:left;margin-left:10px;padding:10px;" id="faces_div"></div> -->

</div>

<div class="vote_link add_ans_class add_ans_link" style="margin-bottom:20px;">
    <div class="mytube">
       <a href="{{BASE_URL}}/add" target="_top">{% trans %}Create your own questions!{% endtrans %}</a>
    </div>
</div>
